[package]
name = "foo"
version = "0.1.0"
authors = ["kszlzj <1363071121@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name="foo"
crate-type=["staticlib"]
